
server:
  port: 8000


logging:
  level:
    root: INFO

spring:
  devtools:
    restart:
      additional-paths: src/main/java

application:
  jwt:
    tokenPrefix: 'Bearer '
    secretKey: zyxwvuzyxwvuzyxwvuabcabcxyzzyxwvuzyxwvuzyxwvuabcabcxyz
    tokenExpirationDays: 1

